import { SectionItem } from './section-item';
import { HexSegment, Segment, RvaSegment, FileOffsetSegment, AsciiSegment, VaSegment } from './segment';
import { DataDirectoryItem } from './data-directory-item';
import { Byte } from './byte';
import { CliFlags } from './cli-flags';
import { Subsystem } from './subsystem';
import { Characteristics } from './characteristics';
import { DllCharacteristics } from './dll-characteristics';
import { EntryPoint } from './entry-point';

export class PortableExecutable {
  public dosHeader: Segment;
  public signatureOffset: FileOffsetSegment;
  public dosStub: Segment;
  public signature: Segment;
  public coffHeader: Segment;
  public characteristics: Characteristics;
  public standardFields: Segment;
  public magicNumber: HexSegment;
  public is64Bit: boolean;
  public addressOfEntryPoint: RvaSegment;
  public ntSpecificFields: Segment;
  public imageBase: HexSegment;
  public subsystem: Subsystem;
  public dllCharacteristics: DllCharacteristics;
  public dataDirectories: Segment;
  public importTableDirectory: DataDirectoryItem;
  public importAddressTableDirectory: DataDirectoryItem;
  public cliHeaderDirectory: DataDirectoryItem;
  public isManaged: boolean;
  public textSectionHeader: Segment;
  public textSectionItem: SectionItem;
  public rsrcSectionHeader: Segment;
  public rsrcSectionItem: SectionItem;
  public relocSectionHeader: Segment;
  public relocSectionItem: SectionItem;
  public importAddressTableSizeDec: number;
  public importAddressTable: Segment;
  public cliHeaderSizeDec: number;
  public cliHeader: Segment;
  public cliFlags: CliFlags;
  public cliMetadataHeaderDirectory: DataDirectoryItem;
  public cliMetadataHeader: Segment;
  public clrVersionSize: HexSegment;
  public clrVersion: AsciiSegment;
  public importTableSizeDec: number;
  public importTable: Segment;
  public entryPoint: Segment;
  public entryPointOpCode: HexSegment;
  public entryPointVa: VaSegment;
  public iatEntryPointRva: RvaSegment;
  public managedEntryPoint: EntryPoint;
  public hexes: Byte[];
}
