resources:
- repo: self
pool:
  vmImage: 'ubuntu-18.04'

steps:

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
  displayName: Install Yarn 1.21.1
  inputs:
    versionSpec: 1.21.1

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
  displayName: yarn install
  inputs:
    arguments: install

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
  displayName: yarn lint
  inputs:
    arguments: lint

- script: |
    sudo apt-get -qq update > /dev/null
    sudo apt-get -y -qq install libxss1 > /dev/null
    sudo apt-get -y -qq install libgtk-3-0 > /dev/null
    sudo apt-get -y -qq install libgdk3.0-cil > /dev/null
  displayName: Install modules required to run headless Chrome

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
  displayName: yarn test-ci
  inputs:
    arguments: test-ci

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
  displayName: yarn build-prod
  inputs:
    arguments: build-prod

- task: geeklearningio.gl-vsts-tasks-file-patch.json-patch-task.JsonPatch@3
  displayName: Version web Artifact
  inputs:
    JsonWorkingDir: 'dist/'
    JsonTargetFilters: environment.json
    JsonPatchContent: |
     = /build => "$(BUILD_BUILDNUMBER)"
     = /commit=> "$(BUILD_SOURCEVERSION)"
    OutputPatchFile: true
    FailIfNoPatchApplied: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact - web
  inputs:
    PathtoPublish: 'dist/'
    ArtifactName: web
    publishLocation: Container

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact - ARM
  inputs:
    PathtoPublish: 'template/template.json'
    ArtifactName: arm
    publishLocation: Container

- task: PublishTestResults@2
  displayName: Publish tests results
  inputs:
    testResultsFiles: 'tests-results/tests-results.xml'
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  displayName: Publish coverage
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage/'
    failIfCoverageEmpty: true
  condition: succeededOrFailed()
